const $ = (s, root=document) => root.querySelector(s);
const LOCAL_PREFIX='calren-cloud-cache-v2-';
const LANG='calren-lang';
const THEME='calren-theme';
const config=window.MARN_CONFIG||{};
const configReady=/^https:\/\/.+\.supabase\.co$/.test(config.SUPABASE_URL||'')&&!!config.SUPABASE_PUBLISHABLE_KEY;
const cloud=configReady&&window.supabase?window.supabase.createClient(config.SUPABASE_URL,config.SUPABASE_PUBLISHABLE_KEY):null;

const translations={ar:{brandSub:'حاسبة الراتب بالساعات',today:'اليوم',unpaid:'المستحقات غير المستلمة',totalHours:'إجمالي الساعات',monthDue:'إجمالي مستحقات الشهر',shiftCount:'عدد الشفتات',hour:'ساعة',shift:'شفت',quickAdd:'إضافة شفت / مهمة جديدة',quickHint:'أدخل ساعات اليوم وسيُحسب المبلغ مباشرة.',date:'التاريخ',hours:'الساعات',minutes:'الدقائق',hourlyRate:'سعر الساعة',expectedAmount:'المبلغ المتوقع',add:'إضافة',addMonth:'إضافة شهر كامل',deleteMonth:'حذف الشهر كامل',calendar:'تقويم الشهر',goToday:'اليوم',workDay:'يوم عمل',autoOff:'إجازة تلقائية',monthOverview:'نظرة عامة على الشهر',received:'المبلغ المستلم',difference:'الفرق',shiftDetails:'تفاصيل الشفتات',time:'الوقت',duration:'المدة',amount:'المبلغ',actions:'الإجراءات',receivedAmount:'المبلغ المستلم (SAR)',markReceived:'تم استلام الراتب',settings:'الإعدادات',downloadJson:'تحميل ملف JSON',importJson:'إضافة ملف JSON',resetData:'إعادة جميع البيانات',language:'اللغة',theme:'لون الواجهة',logout:'تسجيل خروج',editShift:'تعديل الشفت',save:'حفظ'},en:{brandSub:'Hourly salary calculator',today:'Today',unpaid:'Unpaid entitlements',totalHours:'Total hours',monthDue:'Current month due',shiftCount:'Shifts',hour:'hours',shift:'shifts',quickAdd:'Add shift / task',quickHint:'Enter today’s hours and CALREN calculates the amount instantly.',date:'Date',hours:'Hours',minutes:'Minutes',hourlyRate:'Hourly rate',expectedAmount:'Expected amount',add:'Add',addMonth:'Add full month',deleteMonth:'Delete full month',calendar:'Monthly calendar',goToday:'Today',workDay:'Work day',autoOff:'Automatic day off',monthOverview:'Month overview',received:'Received amount',difference:'Difference',shiftDetails:'Shift details',time:'Time',duration:'Duration',amount:'Amount',actions:'Actions',receivedAmount:'Received amount (SAR)',markReceived:'Salary received',settings:'Settings',downloadJson:'Download JSON',importJson:'Import JSON',resetData:'Reset all data',language:'Language',theme:'Interface color',logout:'Log out',editShift:'Edit shift',save:'Save'}};

let lang=localStorage.getItem(LANG)||'ar';
let theme=localStorage.getItem(THEME)||'emerald';
let viewDate=new Date();
let currentUser=null;
let authMode='login';
let state={version:2,shifts:[],months:{},autoOff:[]};
let saveTimer=null;

function emptyState(){return{version:2,shifts:[],months:{},autoOff:[]}}
function cacheKey(){return `${LOCAL_PREFIX}${currentUser?.id||'guest'}`}
function normalize(data){return{version:2,shifts:Array.isArray(data?.shifts)?data.shifts:[],months:data?.months&&typeof data.months==='object'?data.months:{},autoOff:Array.isArray(data?.autoOff)?data.autoOff:[]}}
function readCache(){try{return normalize(JSON.parse(localStorage.getItem(cacheKey())||'null'))}catch{return emptyState()}}
function writeCache(){localStorage.setItem(cacheKey(),JSON.stringify(state))}
function setSync(type,text){const dot=$('#syncDot'),label=$('#syncText');if(!dot||!label)return;dot.className=`sync-dot ${type||''}`.trim();label.textContent=text}
async function loadCloud(){state=readCache();render();if(!cloud||!currentUser)return;setSync('syncing',lang==='ar'?'جارٍ المزامنة...':'Syncing...');const {data,error}=await cloud.from('dashboard_data').select('data').eq('user_id',currentUser.id).maybeSingle();if(error){console.error(error);setSync('error',lang==='ar'?'تعذر الاتصال':'Sync failed');toast(lang==='ar'?'تم عرض آخر نسخة محفوظة محليًا':'Showing the latest local copy');return}if(data?.data)state=normalize(data.data);else await cloud.from('dashboard_data').upsert({user_id:currentUser.id,data:state},{onConflict:'user_id'});writeCache();render();setSync('',lang==='ar'?'تمت المزامنة':'Synced')}
function save(){writeCache();if(!cloud||!currentUser)return;clearTimeout(saveTimer);setSync('syncing',lang==='ar'?'جارٍ الحفظ...':'Saving...');saveTimer=setTimeout(async()=>{const {error}=await cloud.from('dashboard_data').upsert({user_id:currentUser.id,data:state},{onConflict:'user_id'});if(error){console.error(error);setSync('error',lang==='ar'?'تعذر الحفظ':'Save failed');toast(lang==='ar'?'تعذر الحفظ في Supabase':'Cloud save failed')}else setSync('',lang==='ar'?'تم الحفظ':'Saved')},300)}

function key(d){return d.toISOString().slice(0,7)}
function isoLocal(d){const z=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}`}
function money(n){return Number(n||0).toLocaleString(lang==='ar'?'ar-SA':'en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}
function hoursText(n){const h=Math.floor(n),m=Math.round((n-h)*60);return m?`${h}h ${m}m`:`${h}h`}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function monthData(){const k=key(viewDate),shifts=state.shifts.filter(s=>s.date.startsWith(k)),due=shifts.reduce((a,s)=>a+Number(s.amount||0),0),hrs=shifts.reduce((a,s)=>a+Number(s.hours||0)+Number(s.minutes||0)/60,0),received=Number(state.months[k]?.received||0);return{k,shifts,due,hrs,received,diff:received-due,settled:!!state.months[k]?.settled}}
function allUnpaid(){const months=new Set([...Object.keys(state.months),...state.shifts.map(s=>s.date.slice(0,7))]);let sum=0;months.forEach(k=>{const due=state.shifts.filter(s=>s.date.startsWith(k)).reduce((a,s)=>a+Number(s.amount||0),0);const rec=Number(state.months[k]?.received||0);if(!state.months[k]?.settled)sum+=Math.max(0,due-rec)});return sum}

function applyTheme(){document.documentElement.dataset.theme=theme;$('#themeLabel').textContent=theme==='emerald'?'Emerald Green':lang==='ar'?'بنفسجي':'Purple'}
function render(){applyLang();applyTheme();renderToday();renderCalendar();renderTable();renderStats();updateLive()}
function applyLang(){document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.querySelectorAll('[data-i18n]').forEach(e=>e.textContent=translations[lang][e.dataset.i18n]||e.textContent);$('#languageLabel').textContent=lang==='ar'?'العربية':'English';applyAuthLanguage()}
function renderToday(){const d=new Date();$('#todayDate').textContent=d.toLocaleDateString(lang==='ar'?'ar-SA-u-ca-gregory':'en-GB',{year:'numeric',month:'long',day:'numeric'});$('#todayDay').textContent=d.toLocaleDateString(lang==='ar'?'ar-SA':'en-US',{weekday:'long'});$('#shiftDate').value||=isoLocal(d)}
function renderStats(){const m=monthData(),unpaid=allUnpaid();$('#unpaidTotal').textContent=money(unpaid);$('#unpaidStatus').textContent=unpaid>0?(lang==='ar'?'ناقص':'Due'):(lang==='ar'?'كامل':'Complete');$('.danger-card').classList.toggle('has-due',unpaid>0);$('#totalHours').textContent=m.hrs.toFixed(2);$('#monthDue').textContent=money(m.due);$('#shiftCount').textContent=m.shifts.length;$('#sideHours').textContent=m.hrs.toFixed(2);$('#sideShifts').textContent=m.shifts.length;$('#sideDue').textContent=`${money(m.due)} SAR`;$('#sideReceived').textContent=`${money(m.received)} SAR`;$('#receivedAmount').value=m.received||'';setDiff(m.diff);$('#bottomHours').textContent=m.hrs.toFixed(2);$('#bottomShifts').textContent=m.shifts.length}
function setDiff(diff){const status=Math.abs(diff)<.01?(lang==='ar'?'كامل':'Complete'):diff>0?(lang==='ar'?'زائد':'Extra'):(lang==='ar'?'ناقص':'Short');['sideDifference','bottomDifference'].forEach(id=>$('#'+id).textContent=`${diff>0?'+ ':''}${money(diff)} SAR`);['differenceStatus','bottomStatus'].forEach(id=>$('#'+id).textContent=status);$('.overview-row.difference').classList.toggle('negative',diff<0);$('.difference-box').classList.toggle('negative',diff<0)}
function renderCalendar(){const y=viewDate.getFullYear(),m=viewDate.getMonth(),locale=lang==='ar'?'ar-SA-u-ca-gregory':'en-US';$('#calendarTitle').textContent=new Date(y,m,1).toLocaleDateString(locale,{month:'long',year:'numeric'});$('#tableMonthTitle').textContent=$('#calendarTitle').textContent;const names=lang==='ar'?['الأحد','الاثنين','الثلاثاء','الأربعاء','الخميس','الجمعة','السبت']:['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];$('#weekdays').innerHTML=names.map(n=>`<span>${n}</span>`).join('');const first=new Date(y,m,1),start=new Date(y,m,1-first.getDay()),today=isoLocal(new Date()),items=[];for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const iso=isoLocal(d),dayShifts=state.shifts.filter(s=>s.date===iso),total=dayShifts.reduce((a,s)=>a+Number(s.hours)+Number(s.minutes)/60,0),isOff=state.autoOff.includes(iso),cls=['day',d.getMonth()!==m?'muted':'',iso===today?'today':'',dayShifts.length?'worked':'',isOff?'auto-off':''].join(' ');items.push(`<div class="${cls}" data-date="${iso}"><span class="day-number">${d.getDate()}</span>${dayShifts.length?`<span class="day-hours">${hoursText(total)}</span>`:''}${isOff?`<span class="day-note">${lang==='ar'?'إجازة تلقائية':'Auto off'}</span>`:''}</div>`)}$('#calendarGrid').innerHTML=items.join('');document.querySelectorAll('.day').forEach(d=>d.onclick=()=>{$('#shiftDate').value=d.dataset.date;window.scrollTo({top:$('.quick-panel').offsetTop-20,behavior:'smooth'})})}
function renderTable(){const m=monthData(),body=$('#shiftsBody');if(!m.shifts.length){body.innerHTML=`<tr><td colspan="6" class="empty">${lang==='ar'?'لا توجد شفتات في هذا الشهر':'No shifts in this month'}</td></tr>`;return}body.innerHTML=[...m.shifts].sort((a,b)=>b.date.localeCompare(a.date)).map(s=>`<tr><td>${s.date}</td><td>${s.start||'—'}</td><td>${hoursText(Number(s.hours)+Number(s.minutes)/60)}</td><td>${money(s.rate)} SAR</td><td>${money(s.amount)} SAR</td><td><div class="row-actions"><button class="mini-btn" onclick="editShift('${s.id}')">✎</button><button class="mini-btn delete" onclick="deleteShift('${s.id}')">⌫</button></div></td></tr>`).join('')}
function updateLive(){const h=Number($('#shiftHours').value||0),m=Number($('#shiftMinutes').value||0),r=Number($('#hourlyRate').value||0);$('#liveAmount').textContent=`${money((h+m/60)*r)} SAR`}
function enforceSixDayRule(){const dates=[...new Set(state.shifts.map(s=>s.date))].sort();state.autoOff=[];for(let i=0;i<dates.length;i++){let streak=1;for(let j=i;j>0;j--){const a=new Date(dates[j]),b=new Date(dates[j-1]);if((a-b)/86400000===1)streak++;else break}if(streak>=6){const off=new Date(dates[i]);off.setDate(off.getDate()+1);const iso=isoLocal(off);if(!dates.includes(iso)&&!state.autoOff.includes(iso))state.autoOff.push(iso)}}}

$('#shiftForm').onsubmit=e=>{e.preventDefault();const date=$('#shiftDate').value,h=Number($('#shiftHours').value),min=Number($('#shiftMinutes').value),rate=Number($('#hourlyRate').value);if(!date||h+min/60<=0)return toast(lang==='ar'?'أدخل مدة صحيحة':'Enter a valid duration');if(state.autoOff.includes(date))return toast(lang==='ar'?'هذا اليوم إجازة تلقائية بعد 6 أيام عمل':'This is an automatic day off');const data={id:crypto.randomUUID(),date,hours:h,minutes:min,rate,amount:(h+min/60)*rate,start:'—'};state.shifts.push(data);enforceSixDayRule();save();viewDate=new Date(date+'T12:00:00');render();toast(lang==='ar'?'تم حفظ الشفت':'Shift saved')};
document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{const input=b.dataset.step==='hours'?$('#shiftHours'):$('#shiftMinutes'),max=Number(input.max),min=Number(input.min),v=Math.max(min,Math.min(max,Number(input.value)+Number(b.dataset.dir)));input.value=v;updateLive()});['shiftHours','shiftMinutes','hourlyRate'].forEach(id=>$('#'+id).oninput=updateLive);
window.deleteShift=id=>{if(confirm(lang==='ar'?'حذف هذا الشفت؟':'Delete this shift?')){state.shifts=state.shifts.filter(s=>s.id!==id);enforceSixDayRule();save();render()}};
window.editShift=id=>{const s=state.shifts.find(x=>x.id===id);if(!s)return;$('#editId').value=s.id;$('#editDate').value=s.date;$('#editHours').value=s.hours;$('#editMinutes').value=s.minutes;$('#editRate').value=s.rate;$('#editDialog').showModal()};
$('#editForm').onsubmit=e=>{e.preventDefault();const s=state.shifts.find(x=>x.id===$('#editId').value);Object.assign(s,{date:$('#editDate').value,hours:Number($('#editHours').value),minutes:Number($('#editMinutes').value),rate:Number($('#editRate').value)});s.amount=(s.hours+s.minutes/60)*s.rate;enforceSixDayRule();save();$('#editDialog').close();render();toast(lang==='ar'?'تم تعديل الشفت':'Shift updated')};
$('#prevMonth').onclick=()=>{viewDate.setMonth(viewDate.getMonth()-1);render()};$('#nextMonth').onclick=()=>{viewDate.setMonth(viewDate.getMonth()+1);render()};$('#todayBtn').onclick=()=>{viewDate=new Date();render()};
$('#addMonthBtn').onclick=()=>{const y=viewDate.getFullYear(),m=viewDate.getMonth(),days=new Date(y,m+1,0).getDate(),rate=Number($('#hourlyRate').value||25),hours=Number($('#shiftHours').value||5);for(let d=1;d<=days;d++){const date=new Date(y,m,d),iso=isoLocal(date);if(date.getDay()===5||date.getDay()===6||state.shifts.some(s=>s.date===iso)||state.autoOff.includes(iso))continue;state.shifts.push({id:crypto.randomUUID(),date:iso,hours,minutes:0,rate,amount:hours*rate,start:'—'});enforceSixDayRule()}save();render();toast(lang==='ar'?'تمت إضافة أيام الشهر':'Month shifts added')};
$('#deleteMonthBtn').onclick=()=>{if(confirm(lang==='ar'?'حذف جميع بيانات الشهر الحالي؟':'Delete all current month data?')){const k=key(viewDate);state.shifts=state.shifts.filter(s=>!s.date.startsWith(k));delete state.months[k];enforceSixDayRule();save();render()}};
$('#receivedAmount').oninput=()=>{const k=key(viewDate);state.months[k]??={};state.months[k].received=Number($('#receivedAmount').value||0);save();renderStats()};
$('#settleBtn').onclick=()=>{const k=key(viewDate);state.months[k]??={};state.months[k].received=Number($('#receivedAmount').value||0);state.months[k].settled=true;save();renderStats();toast(lang==='ar'?'تم إغلاق مستحقات الشهر':'Month settled')};
function toggleDrawer(open){$('#settingsDrawer').classList.toggle('open',open);$('#settingsDrawer').setAttribute('aria-hidden',String(!open));$('#drawerBackdrop').hidden=!open}$('#settingsBtn').onclick=()=>toggleDrawer(true);$('#drawerClose').onclick=$('#drawerBackdrop').onclick=()=>toggleDrawer(false);
function toggleLang(){lang=lang==='ar'?'en':'ar';localStorage.setItem(LANG,lang);render()}$('#languageBtn').onclick=$('#drawerLanguage').onclick=toggleLang;
$('#themeBtn').onclick=()=>{theme=theme==='emerald'?'purple':'emerald';localStorage.setItem(THEME,theme);applyTheme()};
$('#downloadJson').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='calren-backup.json';a.click();URL.revokeObjectURL(a.href)};
$('#importJson').onchange=async e=>{try{state=normalize(JSON.parse(await e.target.files[0].text()));enforceSixDayRule();save();render();toast(lang==='ar'?'تم استيراد البيانات':'Data imported')}catch{toast(lang==='ar'?'ملف غير صالح':'Invalid file')}};
$('#resetData').onclick=()=>{if(confirm(lang==='ar'?'إعادة جميع البيانات؟':'Reset all data?')){state=emptyState();save();render()}};
$('#exportCsvBtn').onclick=()=>{const rows=[['date','hours','minutes','hourly_rate','amount'],...monthData().shifts.map(s=>[s.date,s.hours,s.minutes,s.rate,s.amount])];const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([rows.map(r=>r.join(',')).join('\n')],{type:'text/csv'}));a.download=`calren-${key(viewDate)}.csv`;a.click()};

function setAuthMessage(message,type=''){const el=$('#authMessage');el.textContent=message||'';el.className=`auth-message ${type}`.trim()}
function setAuthMode(mode){authMode=mode;$('#loginTab').classList.toggle('active',mode==='login');$('#signupTab').classList.toggle('active',mode==='signup');$('#nameField').classList.toggle('hidden',mode!=='signup');$('#authName').required=mode==='signup';$('#forgotPasswordBtn').classList.toggle('hidden',mode!=='login');$('#authSubmitBtn').textContent=mode==='login'?(lang==='ar'?'دخول':'Sign in'):(lang==='ar'?'إنشاء الحساب':'Create account')}
function applyAuthLanguage(){if(!$('#authScreen'))return;$('#authTitle').textContent='CALREN';$('#authSubtitle').textContent=lang==='ar'?'سجّل الدخول للوصول إلى بياناتك من أي جهاز':'Sign in to access your data from any device';$('#loginTab').textContent=lang==='ar'?'تسجيل الدخول':'Sign in';$('#signupTab').textContent=lang==='ar'?'إنشاء حساب':'Create account';$('#nameLabel').textContent=lang==='ar'?'الاسم':'Name';$('#emailLabel').textContent=lang==='ar'?'البريد الإلكتروني':'Email';$('#passwordLabel').textContent=lang==='ar'?'كلمة المرور':'Password';$('#forgotPasswordBtn').textContent=lang==='ar'?'نسيت كلمة المرور':'Forgot password';setAuthMode(authMode)}
function showAuth(){currentUser=null;$('#authScreen').classList.remove('hidden');$('#appShell').classList.add('hidden');applyAuthLanguage()}
async function showApp(user){currentUser=user;$('#authScreen').classList.add('hidden');$('#appShell').classList.remove('hidden');$('#accountEmail').textContent=user.email||'';await loadCloud()}
$('#loginTab').onclick=()=>setAuthMode('login');$('#signupTab').onclick=()=>setAuthMode('signup');
$('#authForm').onsubmit=async e=>{e.preventDefault();if(!cloud)return setAuthMessage(lang==='ar'?'تحقق من إعدادات Supabase في config.js':'Check Supabase settings in config.js','error');const email=$('#authEmail').value.trim(),password=$('#authPassword').value;$('#authSubmitBtn').disabled=true;setAuthMessage(lang==='ar'?'جارٍ التنفيذ...':'Working...');try{if(authMode==='signup'){const fullName=$('#authName').value.trim();const {data,error}=await cloud.auth.signUp({email,password,options:{data:{full_name:fullName}}});if(error)throw error;setAuthMessage(data.session?(lang==='ar'?'تم إنشاء الحساب':'Account created'):(lang==='ar'?'تحقق من بريدك لتأكيد الحساب':'Check your email to confirm the account'),'success')}else{const {error}=await cloud.auth.signInWithPassword({email,password});if(error)throw error}}catch(err){setAuthMessage(err.message,'error')}finally{$('#authSubmitBtn').disabled=false}};
$('#forgotPasswordBtn').onclick=async()=>{const email=$('#authEmail').value.trim();if(!email)return setAuthMessage(lang==='ar'?'اكتب بريدك أولًا':'Enter your email first','error');const {error}=await cloud.auth.resetPasswordForEmail(email,{redirectTo:location.href.split('#')[0]});setAuthMessage(error?error.message:(lang==='ar'?'تم إرسال رابط إعادة التعيين':'Password reset link sent'),error?'error':'success')};
$('.logout').onclick=async()=>{if(cloud)await cloud.auth.signOut()};

applyTheme();applyLang();renderToday();
(async()=>{if(!cloud){showAuth();setAuthMessage(lang==='ar'?'تعذر تهيئة Supabase. تحقق من config.js':'Supabase is not configured. Check config.js','error');return}cloud.auth.onAuthStateChange((_event,session)=>setTimeout(()=>session?.user?showApp(session.user):showAuth(),0));const {data:{session}}=await cloud.auth.getSession();session?.user?await showApp(session.user):showAuth()})();
