const KEY='calren-data-v1';
const i18n={ar:{tagline:'حاسبة الراتب بالساعات',today:'اليوم',welcome:'اعرف مستحقاتك بدقة',description:'سجّل ساعات عملك اليومية، وقارن المبلغ المستحق بما استلمته فعليًا.',unpaid:'المستحقات غير المستلمة',hours:'إجمالي الساعات',hour:'ساعة',monthDue:'مستحقات الشهر الحالي',shifts:'عدد الشفتات',shift:'شفت',quick:'إدخال سريع',addShift:'إضافة شفت / مهمة',date:'التاريخ',hoursInput:'ساعات',minutes:'دقائق',hourRate:'سعر الساعة',expected:'المبلغ المتوقع',add:'إضافة',addMonth:'إضافة شهر كامل',deleteMonth:'حذف الشهر كاملًا',calendar:'تقويم الشهر',todayBtn:'اليوم',overview:'نظرة عامة على الشهر',received:'المبلغ المستلم',difference:'الفرق',workday:'يوم عمل',forcedLeave:'إجازة تلقائية بعد 6 أيام',currentDay:'اليوم الحالي',details:'التفاصيل',shiftDetails:'تفاصيل الشفتات',time:'المدة',amount:'المبلغ',edit:'تعديل',delete:'حذف',saveReceived:'حفظ المبلغ المستلم',closeMonth:'تم استلام الراتب وإغلاق الشهر',export:'تحميل ملف JSON',import:'إضافة ملف JSON',reset:'إعادة جميع البيانات',logout:'تسجيل خروج'},en:{tagline:'Hourly salary calculator',today:'Today',welcome:'Know exactly what you earned',description:'Track daily hours and compare expected salary with what you received.',unpaid:'Unpaid earnings',hours:'Total hours',hour:'hours',monthDue:'Current month earnings',shifts:'Shifts',shift:'shifts',quick:'Quick entry',addShift:'Add shift / task',date:'Date',hoursInput:'Hours',minutes:'Minutes',hourRate:'Hourly rate',expected:'Expected amount',add:'Add',addMonth:'Add full month',deleteMonth:'Delete full month',calendar:'Month calendar',todayBtn:'Today',overview:'Month overview',received:'Received amount',difference:'Difference',workday:'Work day',forcedLeave:'Automatic leave after 6 days',currentDay:'Current day',details:'Details',shiftDetails:'Shift details',time:'Duration',amount:'Amount',edit:'Edit',delete:'Delete',saveReceived:'Save received amount',closeMonth:'Salary received and month closed',export:'Download JSON',import:'Import JSON',reset:'Reset all data',logout:'Log out'}};
let state=load(), cursor=new Date(), lang=localStorage.getItem('calren-lang')||'ar';
const $=s=>document.querySelector(s), money=n=>Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}), keyOf=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`, iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
function load(){try{return JSON.parse(localStorage.getItem(KEY))||{shifts:[],months:{}}}catch{return{shifts:[],months:{}}}} function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function monthData(k){return state.months[k]||(state.months[k]={received:0,closed:false})}
function applyLang(){document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.querySelectorAll('[data-i18n]').forEach(e=>e.textContent=i18n[lang][e.dataset.i18n]);$('#langBtn').textContent=lang==='ar'?'EN':'AR';render()}
function calcShift(s){return (Number(s.hours)+Number(s.minutes)/60)*Number(s.rate)}
function monthShifts(k=keyOf(cursor)){return state.shifts.filter(s=>s.date.startsWith(k)).sort((a,b)=>b.date.localeCompare(a.date))}
function totals(k=keyOf(cursor)){const ss=monthShifts(k),hours=ss.reduce((a,s)=>a+Number(s.hours)+Number(s.minutes)/60,0),due=ss.reduce((a,s)=>a+calcShift(s),0),m=monthData(k);return{ss,hours,due,received:Number(m.received||0),diff:Number(m.received||0)-due,closed:!!m.closed}}
function render(){const now=new Date(),locale=lang==='ar'?'ar-SA-u-ca-gregory':'en-US';$('#todayDate').textContent=now.toLocaleDateString(locale,{day:'numeric',month:'long',year:'numeric'});$('#todayDay').textContent=now.toLocaleDateString(locale,{weekday:'long'});const allDue=Object.keys(state.months).reduce((sum,k)=>{const t=totals(k);return sum+(t.closed?0:Math.max(0,t.due-t.received))},0);const t=totals();$('#unpaidTotal').textContent=money(allDue);$('#hoursTotal').textContent=t.hours.toFixed(2);$('#monthDue').textContent=money(t.due);$('#shiftCount').textContent=t.ss.length;$('#overallStatus').textContent=allDue>.005?(lang==='ar'?'ناقص':'Missing'):(lang==='ar'?'كامل':'Complete');$('#overallStatus').className='status '+(allDue>.005?'negative':'positive');renderCalendar();renderTable();renderSettlement(t)}
function renderCalendar(){const y=cursor.getFullYear(),m=cursor.getMonth(),first=new Date(y,m,1),start=new Date(y,m,1-first.getDay()),names=lang==='ar'?['الأحد','الاثنين','الثلاثاء','الأربعاء','الخميس','الجمعة','السبت']:['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];$('#weekdays').innerHTML=names.map(x=>`<div>${x}</div>`).join('');$('#calendarTitle').textContent=cursor.toLocaleDateString(lang==='ar'?'ar-SA-u-ca-gregory':'en-US',{month:'long',year:'numeric'});let html='',consecutive=0;for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const ds=iso(d),ss=state.shifts.filter(s=>s.date===ds),hrs=ss.reduce((a,s)=>a+Number(s.hours)+Number(s.minutes)/60,0);if(ss.length)consecutive++;else consecutive=0;const forced=consecutive===6&&i<41;const isToday=ds===iso(new Date());html+=`<div class="day ${d.getMonth()!==m?'out':''} ${isToday?'today':''}" data-date="${ds}"><span class="num">${d.getDate()}</span>${hrs?`<span class="hours">${hrs.toFixed(1)}h</span>`:''}${forced?'<span class="leave">غدًا إجازة تلقائية</span>':''}</div>`}$('#calendarDays').innerHTML=html;const t=totals();$('#asideHours').textContent=t.hours.toFixed(2);$('#asideShifts').textContent=t.ss.length;$('#asideDue').textContent=money(t.due)+' SAR';$('#asideReceived').textContent=money(t.received)+' SAR';$('#asideDiff').textContent=money(t.diff)+' SAR'}
function renderTable(){const ss=monthShifts();$('#shiftRows').innerHTML=ss.length?ss.map(s=>`<tr><td>${s.date}</td><td>${s.hours}h ${s.minutes}m</td><td>${money(calcShift(s))} SAR</td><td>${money(s.rate)} SAR</td><td><button class="mini" data-edit="${s.id}">✎</button></td><td><button class="mini delete" data-delete="${s.id}">⌫</button></td></tr>`).join(''):`<tr><td colspan="6" class="empty">${lang==='ar'?'لا توجد شفتات في هذا الشهر':'No shifts this month'}</td></tr>`}
function renderSettlement(t){$('#receivedAmount').value=t.received||'';$('#closeMonth').checked=t.closed;$('#differenceValue').textContent=`${t.diff>=0?'+':''}${money(t.diff)} SAR`;const status=Math.abs(t.diff)<.005?(lang==='ar'?'كامل':'Complete'):t.diff>0?(lang==='ar'?'زائد':'Extra'):(lang==='ar'?'ناقص':'Missing');$('#differenceStatus').textContent=status;$('#differenceValue').style.color=t.diff<-.005?'var(--danger)':'var(--emerald)'}
function toast(msg){const e=$('#toast');e.textContent=msg;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function validateRest(date){const d=new Date(date+'T12:00:00');let count=0;for(let i=1;i<=6;i++){const p=new Date(d);p.setDate(d.getDate()-i);if(state.shifts.some(s=>s.date===iso(p)))count++;else break}return count<6}
function addShift(data,id=null){if(!validateRest(data.date)&&!id){toast(lang==='ar'?'لا يمكن إضافة يوم سابع متتالٍ؛ يجب أن يكون إجازة.':'A seventh consecutive workday is not allowed.');return false}if(id){const i=state.shifts.findIndex(s=>s.id===id);state.shifts[i]={...state.shifts[i],...data}}else state.shifts.push({id:crypto.randomUUID?.()||Date.now().toString(),...data});save();render();return true}
$('#quickForm').addEventListener('submit',e=>{e.preventDefault();if(addShift({date:$('#shiftDate').value,hours:+$('#shiftHours').value,minutes:+$('#shiftMinutes').value,rate:+$('#hourRate').value}))toast(lang==='ar'?'تمت إضافة الشفت':'Shift added')});
function live(){const n=(+$('#shiftHours').value+(+$('#shiftMinutes').value/60))*(+$('#hourRate').value);$('#liveAmount').textContent=money(n)+' SAR'}['shiftHours','shiftMinutes','hourRate'].forEach(id=>$('#'+id).addEventListener('input',live));
$('#prevMonth').onclick=()=>{cursor.setMonth(cursor.getMonth()-1);render()};$('#nextMonth').onclick=()=>{cursor.setMonth(cursor.getMonth()+1);render()};$('#todayMonth').onclick=()=>{cursor=new Date();render()};
$('#calendarDays').onclick=e=>{const day=e.target.closest('.day');if(day){$('#shiftDate').value=day.dataset.date;window.scrollTo({top:$('.quick-panel').offsetTop-20,behavior:'smooth'})}};
$('#shiftRows').onclick=e=>{const del=e.target.closest('[data-delete]'),edit=e.target.closest('[data-edit]');if(del){state.shifts=state.shifts.filter(s=>s.id!==del.dataset.delete);save();render();toast(lang==='ar'?'تم الحذف':'Deleted')}if(edit){const s=state.shifts.find(x=>x.id===edit.dataset.edit);openModal(`<h3>${lang==='ar'?'تعديل الشفت':'Edit shift'}</h3><form id="editForm"><label>${i18n[lang].date}<input id="eDate" type="date" value="${s.date}" required></label><label>${i18n[lang].hoursInput}<input id="eHours" type="number" value="${s.hours}" min="0" max="23"></label><label>${i18n[lang].minutes}<input id="eMinutes" type="number" value="${s.minutes}" min="0" max="59"></label><label>${i18n[lang].hourRate}<input id="eRate" type="number" value="${s.rate}" min="0" step=".01"></label><button class="primary">${lang==='ar'?'حفظ التعديل':'Save'}</button></form>`);$('#editForm').onsubmit=ev=>{ev.preventDefault();addShift({date:$('#eDate').value,hours:+$('#eHours').value,minutes:+$('#eMinutes').value,rate:+$('#eRate').value},s.id);closeModal()}}};
$('#saveReceived').onclick=()=>{const m=monthData(keyOf(cursor));m.received=+$('#receivedAmount').value||0;m.closed=$('#closeMonth').checked;save();render();toast(lang==='ar'?'تم حفظ المبلغ':'Amount saved')};$('#closeMonth').onchange=()=>{monthData(keyOf(cursor)).closed=$('#closeMonth').checked;save();render()};
$('#addFullMonth').onclick=()=>openModal(`<h3>${i18n[lang].addMonth}</h3><form id="monthForm"><label>${lang==='ar'?'ساعات كل يوم':'Hours per day'}<input id="mHours" type="number" min="0" max="23" value="8"></label><label>${i18n[lang].minutes}<input id="mMinutes" type="number" min="0" max="59" value="0"></label><label>${i18n[lang].hourRate}<input id="mRate" type="number" min="0" step=".01" value="${$('#hourRate').value}"></label><label>${lang==='ar'?'أيام العمل (الأحد إلى الخميس)':'Workdays (Sun–Thu)'}</label><button class="primary">${i18n[lang].addMonth}</button></form>`);document.addEventListener('submit',function handler(e){if(e.target.id!=='monthForm')return;e.preventDefault();const y=cursor.getFullYear(),m=cursor.getMonth(),days=new Date(y,m+1,0).getDate();for(let d=1;d<=days;d++){const date=new Date(y,m,d),day=date.getDay();if(day!==5&&day!==6)addShift({date:iso(date),hours:+$('#mHours').value,minutes:+$('#mMinutes').value,rate:+$('#mRate').value})}closeModal();document.removeEventListener('submit',handler);render()});
$('#deleteFullMonth').onclick=()=>{if(confirm(lang==='ar'?'هل تريد حذف جميع بيانات هذا الشهر؟':'Delete all data for this month?')){const k=keyOf(cursor);state.shifts=state.shifts.filter(s=>!s.date.startsWith(k));delete state.months[k];save();render();toast(lang==='ar'?'تم حذف الشهر':'Month deleted')}};
function openModal(html){$('#modalBody').innerHTML=html;$('#modal').hidden=false}function closeModal(){$('#modal').hidden=true}$('#modalClose').onclick=closeModal;$('#modal').onclick=e=>{if(e.target===$('#modal'))closeModal()};
$('#settingsBtn').onclick=()=>$('#settingsMenu').classList.toggle('open');document.addEventListener('click',e=>{if(!e.target.closest('.menu-wrap'))$('#settingsMenu').classList.remove('open')});
$('#settingsMenu').onclick=e=>{const a=e.target.closest('[data-action]')?.dataset.action;if(!a)return;if(a==='export'){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),x=document.createElement('a');x.href=u;x.download='CALREN-backup.json';x.click();URL.revokeObjectURL(u)}if(a==='import')$('#importInput').click();if(a==='reset'&&confirm(lang==='ar'?'سيتم حذف جميع البيانات. هل أنت متأكد؟':'All data will be deleted. Continue?')){state={shifts:[],months:{}};save();render()}if(a==='logout')toast(lang==='ar'?'تم تسجيل الخروج محليًا':'Logged out locally')};
$('#importInput').onchange=async e=>{try{const x=JSON.parse(await e.target.files[0].text());if(!Array.isArray(x.shifts)||typeof x.months!=='object')throw 0;state=x;save();render();toast(lang==='ar'?'تم استيراد البيانات':'Data imported')}catch{alert(lang==='ar'?'ملف غير صالح':'Invalid file')}};
$('#langBtn').onclick=()=>{lang=lang==='ar'?'en':'ar';localStorage.setItem('calren-lang',lang);applyLang()};$('#themeBtn').onclick=()=>{const light=document.documentElement.dataset.theme==='light';document.documentElement.dataset.theme=light?'':'light';localStorage.setItem('calren-theme',light?'dark':'light')};
$('#shiftDate').value=iso(new Date());if(localStorage.getItem('calren-theme')==='light')document.documentElement.dataset.theme='light';live();applyLang();
